version: '2'
services:
    express:
        build: ./
        image: anthony:nodejs-mongodb-composed-express
        container_name: anthony-nodejs-mongodb-composed-express
        links:
            - database:db
        environment:
            MONGODB_URL: mongodb://db:27017
        ports:
            - 49876:8080
        volumes:
            - ./src:/src
            - /src/node_modules
    database:
        image: mongo:3.2
        container_name: anthony-nodejs-mongodb-composed-database
        volumes:
            - ./mongodb:/data/db
